Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -34,11 +34,11 @@ jobs:
       - name: Build Electron App for ${{ matrix.os }}
         run: |
           if [ "${{ matrix.os }}" == "macos-latest" ]; then
-            npm run build -- --mac
+            npm run build -- --mac || { echo "Mac build failed"; exit 1; }
           elif [ "${{ matrix.os }}" == "windows-latest" ]; then
-            npm run build -- --win
+            npm run build -- --win || { echo "Windows build failed"; exit 1; }
           elif [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
-            npm run build -- --linux
+            npm run build -- --linux || { echo "Linux build failed"; exit 1; }
           fi
           DIST_PATH="./dist/${{ matrix.os }}"
           mkdir -p "$DIST_PATH"
@@ -61,6 +61,10 @@ jobs:
         run: |
           DIST_PATH="./dist/${{ matrix.os }}"
           APP_FILES=$(find "$DIST_PATH" -name "*.*" -type f)
+          if [ -z "$APP_FILES" ]; then
+            echo "Error: No files found in $DIST_PATH for ${matrix.os}."
+            exit 1
+          fi
           echo "APP_FILES=$APP_FILES" >> $GITHUB_ENV
         shell: bash
 
